### ISSUE TITLE
OAuth fails after application times out

### ISSUE THREAD

**Issue by mgorenberg** [mrzmyr/angular-google-plus#13]
After an hour of inactivity, my app times out and returns the user to the log-in page.  If, here, the user attempts to use the google+ sign-in, they receive back an error code 401, with a message of 'Invalid Credentials'.  If the time at which the app times out is shortened (to, for instance, 10 seconds), then in that case, the google+ sign-in appears to work fine.

**Comment by mrzmyr** [comment]
hey @mgorenberg , can you provide a [plnkr.co](http://plnkr.co) to make your issue more clear?
Thanks

**Comment by mrzmyr** [comment]
Closing this for now, if there is still an issue with this, just create a new issue.
