### ISSUE TITLE
How to restore the session when the page is refreshed

### ISSUE THREAD

**Issue by RoelRoel** [mrzmyr/angular-google-plus#18]
How can I get the allready logged in user when the page is refreshed?

https://developers.google.com/+/web/signin/session-state

**Comment by RoelRoel** [comment]
This sucks

**Comment by mrzmyr** [comment]
hey @RoelRoel, can you provide a [plnkr.co](http://plnkr.co) to make your issue more clear?
Thanks

**Comment by mrzmyr** [comment]
Closing this for now, if there is still an issue with this, just create a new issue.
