### ISSUE TITLE
I keep receiving gapi is not defined error.

### ISSUE THREAD

**Issue by shreejibawa** [mrzmyr/angular-google-plus#20]
I logged in. Closed browser window. And Opened my webapp again and I receive this error. 

![capture](https://cloud.githubusercontent.com/assets/8849256/8783423/5768578a-2f39-11e5-800d-ee7e5976e09c.PNG)

**Comment by hpedrorodrigues** [comment]
Probably could not load the client.js file and you should have also received this error:

`GET https://apis.google.com/js/client.js net::ERR_CONNECTION_REFUSED`

Possibly you must have had some connection problem.

**Comment by hhoechtl** [comment]
I'm also having this issue and as far as I can see, the problem is, that the GooglePlus module doesn't wait for the async API client to be loaded.

**Comment by mrzmyr** [comment]
@hhoechtl, thats correct. There is currently no checking for the async `client.js` call. To avoid this issues you can try to load your Angular app after loading external calls are finished.

**Comment by Calzzetta** [comment]
Hi @mrzmyr,

I solved it using onload command:
`https://apis.google.com/js/client.js?onload=gapi_ready`

Then I created a global function after disableServerSide:
```
gapi_ready = function () {
    ready = true;
};
```

Then the a new GooglePlus function:

```
f.prototype.isGAPIReady = function () {
    var a = b.defer();
    var check_ready = function() {
        if(ready) {
            a.resolve(ready);
        } else {
            d(check_ready, 300);
        }
    };

    check_ready();
    return a.promise;
};
```

Usage example:
```
GooglePlus.isGAPIReady().then(function () {
    GooglePlus.login().then(function (authResult) {
        console.log(authResult);
    }, function (err) {
        console.log(err);
    });
});
```

Best regards,
Calzzetta

**Comment by mrzmyr** [comment]
Looks like @Calzzetta brought up a way to fix this. If you still have issues with this just create a new issue.
