### ISSUE TITLE
Bower Version Appears Different

### ISSUE THREAD

**Issue by rtucker88** [mrzmyr/angular-google-plus#21]
The version being pulled from Bower is marked 0.1.2, but the files appear different. I noticed this issue when I tried to use the server side sign-in support.

**Comment by mrzmyr** [comment]
After browsing though the commit's I figured out that this is a mistake in the release.
As you can see in the commits 573dcecf4301c5541a86564c0fe9d8f46ccdb422 and e4854b179a6c5981cd5498c3eb676ccce26a1aae.
