### ISSUE TITLE
Not able to get email address

### ISSUE THREAD

**Issue by parth23** [mrzmyr/angular-google-plus#25]

**Comment by humpedli** [comment]
Add `GooglePlusProvider.setScopes('https://www.googleapis.com/auth/userinfo.email');` line to you angular config function and it will work. If you want to use another data too, extend setScopes string parameter with another scope URLs separated by spaces.

**Comment by mrzmyr** [comment]
Thanks for the help @humpedli.
@parth23, please read about [scopes here](https://developers.google.com/+/web/api/rest/oauth#authorization-scopes). 
More about can be found [here in the source](https://github.com/mrzmyr/angular-google-plus/blob/master/src/angular-google-plus.js#L56) and how to use it can be looked up [in the tests](https://github.com/mrzmyr/angular-google-plus/blob/master/test/unit/angular-google-plus.spec.js#L89).
